package com.app.ned.kinmen.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.app.ned.kinmen.db.Repo;
import com.app.ned.kinmen.db.User;

import com.app.ned.kinmen.db.RepoDao;
import com.app.ned.kinmen.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig repoDaoConfig;
    private final DaoConfig userDaoConfig;

    private final RepoDao repoDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        repoDaoConfig = daoConfigMap.get(RepoDao.class).clone();
        repoDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        repoDao = new RepoDao(repoDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Repo.class, repoDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        repoDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public RepoDao getRepoDao() {
        return repoDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
